/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import * as THREE from 'three';

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/calc_model.glb');
  const material1 = new THREE.MeshStandardMaterial({color: 0xe1e6f0}); 

  useFrame(()=> {
   // console.log(nodes); 
  }


  )


  return (
    <group ref={group} {...props} dispose={null} scale={0.5}>
      <mesh geometry={nodes.BODY.geometry} material={nodes.BODY.material} position={[-0.74, 0.3, 1.07]} rotation={[-0.01, 0, 0]} />
      {console.log(group.current)}
      <mesh geometry={nodes.DISPLAY.geometry} material={nodes.DISPLAY.material} position={[-0.57, 0.39, -0.86]} rotation={[-0.01, 0, 0]} scale={[0.98, 1, 1]} />
      <mesh geometry={nodes.BTN_4.geometry} material={nodes.BTN_4.material} position={[-0.63, 0.41, 0.23]} rotation={[-0.01, 0, 0]} scale={[0.9, 1, 0.88]} />
      <mesh geometry={nodes.BTN_7.geometry} material={nodes.BTN_7.material} position={[-0.63, 0.4, -0.11]} rotation={[-0.01, 0, 0]} scale={[0.9, 1, 0.88]} />
      <mesh geometry={nodes.STAND.geometry} material={nodes.STAND.material} position={[-0.64, -0.56, -1.69]} rotation={[1.3, 0, 0]} />
      <mesh geometry={nodes.BTN_CLEAR.geometry} material={nodes.BTN_CLEAR.material} position={[-0.63, 0.4, -0.44]} rotation={[-0.01, 0, 0]} scale={[0.9, 1, 0.9]} />
      <mesh onClick={()=>alert("hey")} geometry={nodes.BTN_SQRT.geometry} material={material1} position={[-0.24, 0.45, -0.48]} rotation={[3.13, 0, Math.PI]} scale={[-0.85, -0.11, -0.78]} />
      <mesh geometry={nodes.BTN_8.geometry} material={nodes.BTN_8.material} material-color={"#ff0000"} position={[-0.28, 0.4, -0.11]} rotation={[-0.01, 0, 0]} scale={[0.88, 1, 0.88]} />
      <mesh geometry={nodes.BTN_5.geometry} material={nodes.BTN_5.material} position={[-0.28, 0.41, 0.23]} rotation={[-0.01, 0, 0]} scale={[0.88, 1, 0.88]} />
      <mesh geometry={nodes.BTN_2.geometry} material={nodes.BTN_2.material} position={[-0.24, 0.46, 0.52]} rotation={[3.13, 0, Math.PI]} scale={[-0.89, -0.1, -0.82]} />
      <mesh geometry={nodes.BTN_0.geometry} material={nodes.BTN_0.material} position={[-0.63, 0.41, 0.9]} rotation={[-0.01, 0, 0]} scale={[0.9, 1, 0.9]} />
      <mesh geometry={nodes.BTN_1.geometry} material={nodes.BTN_1.material} position={[-0.63, 0.41, 0.56]} rotation={[-0.01, 0, 0]} scale={[0.9, 1, 0.88]} />
      <mesh geometry={nodes.BTN_DECIMAL.geometry} material={nodes.BTN_DECIMAL.material} position={[-0.21, 0.47, 0.85]} rotation={[3.13, 0, Math.PI]} scale={[-0.21, -0.05, -0.16]} />
      <mesh geometry={nodes.BTN_NEG.geometry} material={nodes.BTN_NEG.material} position={[0.05, 0.41, 0.9]} rotation={[-0.01, 0, 0]} scale={[0.88, 1, 0.9]} />
      <mesh geometry={nodes.BTN_3.geometry} material={nodes.BTN_3.material} position={[0.05, 0.41, 0.56]} rotation={[-0.01, 0, 0]} scale={[0.88, 1, 0.88]} />
      <mesh geometry={nodes.BTN_6.geometry} material={nodes.BTN_6.material} position={[0.05, 0.41, 0.23]} rotation={[-0.01, 0, 0]} scale={[0.88, 1, 0.88]} />
      <mesh geometry={nodes.BTN_9.geometry} material={nodes.BTN_9.material} position={[0.05, 0.4, -0.11]} rotation={[-0.01, 0, 0]} scale={[0.88, 1, 0.88]} />
      <mesh geometry={nodes.BTN_PWR.geometry} material={nodes.BTN_PWR.material} position={[0.05, 0.4, -0.44]} rotation={[-0.01, 0, 0]} scale={[0.88, 1, 0.9]} />
      <mesh geometry={nodes.BTN_DIV.geometry} material={nodes.BTN_DIV.material} position={[0.42, 0.45, -0.46]} rotation={[3.13, 0, Math.PI]} scale={[-0.68, -0.13, -0.63]} />
      <mesh geometry={nodes.BTN_MULT.geometry} material={nodes.BTN_MULT.material} position={[0.46, 0.45, -0.17]} rotation={[3.13, 0, Math.PI]} scale={[-0.72, -0.1, -0.67]} />
      <mesh geometry={nodes.BTN_SUBTRACT.geometry} material={nodes.BTN_SUBTRACT.material} position={[0.4, 0.46, 0.21]} rotation={[3.13, 0, Math.PI]} scale={[-0.21, -0.13, -0.13]} />
      <mesh geometry={nodes.BTN_ADD.geometry} material={nodes.BTN_ADD.material} position={[0.38, 0.41, 0.56]} rotation={[-0.01, 0, 0]} scale={[0.9, 1, 0.88]} />
      <mesh geometry={nodes.BTN_EQUAL.geometry} material={nodes.BTN_EQUAL.material} position={[0.38, 0.41, 0.9]} rotation={[-0.01, 0, 0]} scale={[0.9, 1, 0.9]} />
    </group>
  )
}

useGLTF.preload('/calc_model.glb')
